parameters:
#    whereis_hello.example.class: Whereis\HelloBundle\Example

services:
#    whereis_hello.example:
#        class: %whereis_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
